// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgProto/msgdef.proto

package com.go.client.socket.proto.message;

public final class Msgdef {
  private Msgdef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code msg.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Null = 0;</code>
     */
    Null(0),
    /**
     * <code>Ping = 100;</code>
     */
    Ping(100),
    /**
     * <code>Pong = 101;</code>
     */
    Pong(101),
    /**
     * <code>ClientSyncTimeReq = 998;</code>
     */
    ClientSyncTimeReq(998),
    /**
     * <code>ClientSyncTimeRes = 999;</code>
     */
    ClientSyncTimeRes(999),
    /**
     * <code>LoginReq = 1000;</code>
     */
    LoginReq(1000),
    /**
     * <code>LoginRes = 1001;</code>
     */
    LoginRes(1001),
    /**
     * <pre>
     *一下为主动推送消息
     * </pre>
     *
     * <code>SyncStart = 5000;</code>
     */
    SyncStart(5000),
    /**
     * <code>LoadFinish = 5001;</code>
     */
    LoadFinish(5001),
    /**
     * <pre>
     *QueueSerivce  20001-30000
     * </pre>
     *
     * <code>AddQueueReq = 20001;</code>
     */
    AddQueueReq(20001),
    /**
     * <code>AddQueueRes = 20002;</code>
     */
    AddQueueRes(20002),
    /**
     * <code>QuitQueueReq = 20003;</code>
     */
    QuitQueueReq(20003),
    /**
     * <code>QuitQueueRes = 20004;</code>
     */
    QuitQueueRes(20004),
    /**
     * <code>MatchReq = 20005;</code>
     */
    MatchReq(20005),
    /**
     * <code>MatchRes = 20006;</code>
     */
    MatchRes(20006),
    /**
     * <pre>
     *RoomSercice 10001 -  20000
     * </pre>
     *
     * <code>CreateRoomReq = 10001;</code>
     */
    CreateRoomReq(10001),
    /**
     * <code>CreateRoomRes = 10002;</code>
     */
    CreateRoomRes(10002),
    /**
     * <code>AddRoomReq = 10003;</code>
     */
    AddRoomReq(10003),
    /**
     * <code>AddRoomRes = 10004;</code>
     */
    AddRoomRes(10004),
    /**
     * <code>QuitRoomReq = 10005;</code>
     */
    QuitRoomReq(10005),
    /**
     * <code>QuitRoomRes = 10006;</code>
     */
    QuitRoomRes(10006),
    /**
     * <code>RadioOtherAddRoomRes = 10007;</code>
     */
    RadioOtherAddRoomRes(10007),
    /**
     * <pre>
     *TableService 30001 - 40000
     * </pre>
     *
     * <code>AddTableReq = 30001;</code>
     */
    AddTableReq(30001),
    /**
     * <code>AddTableRes = 30002;</code>
     */
    AddTableRes(30002),
    /**
     * <code>ClientConnectedStatus = 30003;</code>
     */
    ClientConnectedStatus(30003),
    /**
     * <pre>
     *FriendService 40001 - 50000
     * </pre>
     *
     * <code>FriendListReq = 40001;</code>
     */
    FriendListReq(40001),
    /**
     * <code>FriendListRes = 40002;</code>
     */
    FriendListRes(40002),
    /**
     * <code>NoticeFriendOnLine = 40003;</code>
     */
    NoticeFriendOnLine(40003),
    /**
     * <code>NoticeFiendOffLine = 40004;</code>
     */
    NoticeFiendOffLine(40004),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Null = 0;</code>
     */
    public static final int Null_VALUE = 0;
    /**
     * <code>Ping = 100;</code>
     */
    public static final int Ping_VALUE = 100;
    /**
     * <code>Pong = 101;</code>
     */
    public static final int Pong_VALUE = 101;
    /**
     * <code>ClientSyncTimeReq = 998;</code>
     */
    public static final int ClientSyncTimeReq_VALUE = 998;
    /**
     * <code>ClientSyncTimeRes = 999;</code>
     */
    public static final int ClientSyncTimeRes_VALUE = 999;
    /**
     * <code>LoginReq = 1000;</code>
     */
    public static final int LoginReq_VALUE = 1000;
    /**
     * <code>LoginRes = 1001;</code>
     */
    public static final int LoginRes_VALUE = 1001;
    /**
     * <pre>
     *一下为主动推送消息
     * </pre>
     *
     * <code>SyncStart = 5000;</code>
     */
    public static final int SyncStart_VALUE = 5000;
    /**
     * <code>LoadFinish = 5001;</code>
     */
    public static final int LoadFinish_VALUE = 5001;
    /**
     * <pre>
     *QueueSerivce  20001-30000
     * </pre>
     *
     * <code>AddQueueReq = 20001;</code>
     */
    public static final int AddQueueReq_VALUE = 20001;
    /**
     * <code>AddQueueRes = 20002;</code>
     */
    public static final int AddQueueRes_VALUE = 20002;
    /**
     * <code>QuitQueueReq = 20003;</code>
     */
    public static final int QuitQueueReq_VALUE = 20003;
    /**
     * <code>QuitQueueRes = 20004;</code>
     */
    public static final int QuitQueueRes_VALUE = 20004;
    /**
     * <code>MatchReq = 20005;</code>
     */
    public static final int MatchReq_VALUE = 20005;
    /**
     * <code>MatchRes = 20006;</code>
     */
    public static final int MatchRes_VALUE = 20006;
    /**
     * <pre>
     *RoomSercice 10001 -  20000
     * </pre>
     *
     * <code>CreateRoomReq = 10001;</code>
     */
    public static final int CreateRoomReq_VALUE = 10001;
    /**
     * <code>CreateRoomRes = 10002;</code>
     */
    public static final int CreateRoomRes_VALUE = 10002;
    /**
     * <code>AddRoomReq = 10003;</code>
     */
    public static final int AddRoomReq_VALUE = 10003;
    /**
     * <code>AddRoomRes = 10004;</code>
     */
    public static final int AddRoomRes_VALUE = 10004;
    /**
     * <code>QuitRoomReq = 10005;</code>
     */
    public static final int QuitRoomReq_VALUE = 10005;
    /**
     * <code>QuitRoomRes = 10006;</code>
     */
    public static final int QuitRoomRes_VALUE = 10006;
    /**
     * <code>RadioOtherAddRoomRes = 10007;</code>
     */
    public static final int RadioOtherAddRoomRes_VALUE = 10007;
    /**
     * <pre>
     *TableService 30001 - 40000
     * </pre>
     *
     * <code>AddTableReq = 30001;</code>
     */
    public static final int AddTableReq_VALUE = 30001;
    /**
     * <code>AddTableRes = 30002;</code>
     */
    public static final int AddTableRes_VALUE = 30002;
    /**
     * <code>ClientConnectedStatus = 30003;</code>
     */
    public static final int ClientConnectedStatus_VALUE = 30003;
    /**
     * <pre>
     *FriendService 40001 - 50000
     * </pre>
     *
     * <code>FriendListReq = 40001;</code>
     */
    public static final int FriendListReq_VALUE = 40001;
    /**
     * <code>FriendListRes = 40002;</code>
     */
    public static final int FriendListRes_VALUE = 40002;
    /**
     * <code>NoticeFriendOnLine = 40003;</code>
     */
    public static final int NoticeFriendOnLine_VALUE = 40003;
    /**
     * <code>NoticeFiendOffLine = 40004;</code>
     */
    public static final int NoticeFiendOffLine_VALUE = 40004;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return Null;
        case 100: return Ping;
        case 101: return Pong;
        case 998: return ClientSyncTimeReq;
        case 999: return ClientSyncTimeRes;
        case 1000: return LoginReq;
        case 1001: return LoginRes;
        case 5000: return SyncStart;
        case 5001: return LoadFinish;
        case 20001: return AddQueueReq;
        case 20002: return AddQueueRes;
        case 20003: return QuitQueueReq;
        case 20004: return QuitQueueRes;
        case 20005: return MatchReq;
        case 20006: return MatchRes;
        case 10001: return CreateRoomReq;
        case 10002: return CreateRoomRes;
        case 10003: return AddRoomReq;
        case 10004: return AddRoomRes;
        case 10005: return QuitRoomReq;
        case 10006: return QuitRoomRes;
        case 10007: return RadioOtherAddRoomRes;
        case 30001: return AddTableReq;
        case 30002: return AddTableRes;
        case 30003: return ClientConnectedStatus;
        case 40001: return FriendListReq;
        case 40002: return FriendListRes;
        case 40003: return NoticeFriendOnLine;
        case 40004: return NoticeFiendOffLine;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Msgdef.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:msg.MsgType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025msgProto/msgdef.proto\022\003msg*\256\004\n\007MsgType" +
      "\022\010\n\004Null\020\000\022\010\n\004Ping\020d\022\010\n\004Pong\020e\022\026\n\021Client" +
      "SyncTimeReq\020\346\007\022\026\n\021ClientSyncTimeRes\020\347\007\022\r" +
      "\n\010LoginReq\020\350\007\022\r\n\010LoginRes\020\351\007\022\016\n\tSyncStar" +
      "t\020\210\'\022\017\n\nLoadFinish\020\211\'\022\021\n\013AddQueueReq\020\241\234\001" +
      "\022\021\n\013AddQueueRes\020\242\234\001\022\022\n\014QuitQueueReq\020\243\234\001\022" +
      "\022\n\014QuitQueueRes\020\244\234\001\022\016\n\010MatchReq\020\245\234\001\022\016\n\010M" +
      "atchRes\020\246\234\001\022\022\n\rCreateRoomReq\020\221N\022\022\n\rCreat" +
      "eRoomRes\020\222N\022\017\n\nAddRoomReq\020\223N\022\017\n\nAddRoomR" +
      "es\020\224N\022\020\n\013QuitRoomReq\020\225N\022\020\n\013QuitRoomRes\020\226" +
      "N\022\031\n\024RadioOtherAddRoomRes\020\227N\022\021\n\013AddTable" +
      "Req\020\261\352\001\022\021\n\013AddTableRes\020\262\352\001\022\033\n\025ClientConn" +
      "ectedStatus\020\263\352\001\022\023\n\rFriendListReq\020\301\270\002\022\023\n\r" +
      "FriendListRes\020\302\270\002\022\030\n\022NoticeFriendOnLine\020" +
      "\303\270\002\022\030\n\022NoticeFiendOffLine\020\304\270\002B\007Z\005.;msgb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
